### ISSUE TITLE
Bug with FeatureCollection.fromJson

### ISSUE THREAD

**Issue by Lerobindesbois** [divvitco/geodart#8]
Your package is super interesting. but the FeatureCollection.fromJson constructor doesn't work perfectly. Use GoeJson, which represents hydroelectric lines in Quebec, Canada.

It works fine with geojson_vi, turf packages and the same geojson file, but there is no calculation method like yours.

Use the following file for your tests.

_**Sorry for me english !**_

[ligne_HydroQc_Pylone_WGS84_EPSG4326.geojson.zip](https://github.com/divvitco/geodart/files/10981950/ligne_HydroQc_Pylone_WGS84_EPSG4326.geojson.zip)

**Comment by ntatko** [comment]
Interesting! Thanks for reaching out, and I'm sorry for not getting back sooner. Lemme try this and get back to you.

**Comment by ntatko** [comment]
Looks like the multilinestring `fromJson` method is broken. Fixing now.

**Comment by ntatko** [comment]
available in 0.3.1
